/**
 * pvz-service
 * Plants vs Zombies Info API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AdventureRef } from "./adventureRef";

export interface Level {
  _id?: string;
  level: string;
  unlock: Array<string>;
  ref: AdventureRef;
  is_minigame: boolean;
  notes?: string;
}
