/**
 * pvz-service
 * Plants vs Zombies Info API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Usage } from "./usage";
import { PlantToughness } from "./plantToughness";
import { Production } from "./production";
import { Effect } from "./effect";
import { Recharge } from "./recharge";
import { Damage } from "./damage";

export interface PlantPartial {
  production?: Array<Production>;
  toughness?: PlantToughness;
  damage?: Array<Damage>;
  damage_notes?: string;
  range?: string;
  usage?: Array<Usage>;
  effect?: Effect;
  firing_speed?: string;
  special?: string;
  constraint?: Array<string>;
  cost?: number;
  recharge?: Recharge;
  number?: number;
  name?: string;
  description?: string;
  text?: string;
}
