/**
 * pvz-service
 * Plants vs Zombies Info API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PuzzleCategory } from "./puzzleCategory";

export interface Puzzle {
  _id?: string;
  name: string;
  category: PuzzleCategory;
  with_streak?: boolean;
}
