/**
 * pvz-service
 * Plants vs Zombies Info API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Speed } from "./speed";
import { ZombieToughness } from "./zombieToughness";

export interface ZombiePartial {
  description?: string;
  toughness_notes?: { [key: string]: ZombieToughness };
  speed?: Array<Speed>;
  speed_notes?: string;
  special?: string;
  weakness?: Array<string>;
  constraint?: string;
  number?: number;
  name?: string;
  text?: string;
  toughness?: ZombieToughness;
}
